DEF_INSTR(Shl,"shl" )
DEF_INSTR(Shr,"shr" )
DEF_INSTR(Ror,"ror" )
DEF_INSTR(Xbn,"xbn" )
DEF_INSTR(Jr,"jr"  )
DEF_INSTR(Jalr,"jalr")
DEF_INSTR(Stl,"stl" )
DEF_INSTR(Sth,"sth" )
DEF_INSTR(Stw,"stw" )
DEF_INSTR(Cmp,"cmp" )
DEF_INSTR(Ldl,"ldl" )
DEF_INSTR(Ldh,"ldh" )
DEF_INSTR(Ldw,"ldw" )
DEF_INSTR(Out,"out" )
DEF_INSTR(Mul,"mul" )
DEF_INSTR(And,"and" )
DEF_INSTR(Or,"or"  )
DEF_INSTR(Xor,"xor" )
DEF_INSTR(Bic,"bic" )
DEF_INSTR(Not,"not" )
DEF_INSTR(Sh,"sh"  )
DEF_INSTR(In,"in"  )
DEF_INSTR(Add,"add" )
DEF_INSTR(Sub,"sub" )
DEF_INSTR(Movb,"movb")
DEF_INSTR(Addb,"addb")
DEF_INSTR(Subb,"subb")
DEF_INSTR(B,"b"   )
DEF_INSTR(Bal,"bal" )
DEF_INSTR(Bz,"bz"  )
DEF_INSTR(Bnz,"bnz" )
DEF_INSTR(Blz,"blz" )
DEF_INSTR(Bgez,"bgez")

